// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubbleDatabase) DeepCopyInto(out *HubbleDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubbleDatabase.
func (in *HubbleDatabase) DeepCopy() *HubbleDatabase {
	if in == nil {
		return nil
	}
	out := new(HubbleDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HubbleDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubbleDatabaseList) DeepCopyInto(out *HubbleDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HubbleDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubbleDatabaseList.
func (in *HubbleDatabaseList) DeepCopy() *HubbleDatabaseList {
	if in == nil {
		return nil
	}
	out := new(HubbleDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HubbleDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubbleDatabaseSpec) DeepCopyInto(out *HubbleDatabaseSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubbleDatabaseSpec.
func (in *HubbleDatabaseSpec) DeepCopy() *HubbleDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(HubbleDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubbleDatabaseStatus) DeepCopyInto(out *HubbleDatabaseStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubbleDatabaseStatus.
func (in *HubbleDatabaseStatus) DeepCopy() *HubbleDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(HubbleDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubbleDeveloperDatabase) DeepCopyInto(out *HubbleDeveloperDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubbleDeveloperDatabase.
func (in *HubbleDeveloperDatabase) DeepCopy() *HubbleDeveloperDatabase {
	if in == nil {
		return nil
	}
	out := new(HubbleDeveloperDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HubbleDeveloperDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubbleDeveloperDatabaseList) DeepCopyInto(out *HubbleDeveloperDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HubbleDeveloperDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubbleDeveloperDatabaseList.
func (in *HubbleDeveloperDatabaseList) DeepCopy() *HubbleDeveloperDatabaseList {
	if in == nil {
		return nil
	}
	out := new(HubbleDeveloperDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HubbleDeveloperDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubbleDeveloperDatabaseSpec) DeepCopyInto(out *HubbleDeveloperDatabaseSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubbleDeveloperDatabaseSpec.
func (in *HubbleDeveloperDatabaseSpec) DeepCopy() *HubbleDeveloperDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(HubbleDeveloperDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubbleDeveloperDatabaseStatus) DeepCopyInto(out *HubbleDeveloperDatabaseStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubbleDeveloperDatabaseStatus.
func (in *HubbleDeveloperDatabaseStatus) DeepCopy() *HubbleDeveloperDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(HubbleDeveloperDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubblePolicyReference) DeepCopyInto(out *HubblePolicyReference) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubblePolicyReference.
func (in *HubblePolicyReference) DeepCopy() *HubblePolicyReference {
	if in == nil {
		return nil
	}
	out := new(HubblePolicyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HubblePolicyReference) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubblePolicyReferenceList) DeepCopyInto(out *HubblePolicyReferenceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HubblePolicyReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubblePolicyReferenceList.
func (in *HubblePolicyReferenceList) DeepCopy() *HubblePolicyReferenceList {
	if in == nil {
		return nil
	}
	out := new(HubblePolicyReferenceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HubblePolicyReferenceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubblePolicyReferenceSpec) DeepCopyInto(out *HubblePolicyReferenceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubblePolicyReferenceSpec.
func (in *HubblePolicyReferenceSpec) DeepCopy() *HubblePolicyReferenceSpec {
	if in == nil {
		return nil
	}
	out := new(HubblePolicyReferenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubblePolicyReferenceStatus) DeepCopyInto(out *HubblePolicyReferenceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubblePolicyReferenceStatus.
func (in *HubblePolicyReferenceStatus) DeepCopy() *HubblePolicyReferenceStatus {
	if in == nil {
		return nil
	}
	out := new(HubblePolicyReferenceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubbleRole) DeepCopyInto(out *HubbleRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubbleRole.
func (in *HubbleRole) DeepCopy() *HubbleRole {
	if in == nil {
		return nil
	}
	out := new(HubbleRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HubbleRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubbleRoleList) DeepCopyInto(out *HubbleRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HubbleRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubbleRoleList.
func (in *HubbleRoleList) DeepCopy() *HubbleRoleList {
	if in == nil {
		return nil
	}
	out := new(HubbleRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HubbleRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubbleRoleSpec) DeepCopyInto(out *HubbleRoleSpec) {
	*out = *in
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DevDatabases != nil {
		in, out := &in.DevDatabases, &out.DevDatabases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DatalakeGrants != nil {
		in, out := &in.DatalakeGrants, &out.DatalakeGrants
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DatawarehouseGrants != nil {
		in, out := &in.DatawarehouseGrants, &out.DatawarehouseGrants
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubbleRoleSpec.
func (in *HubbleRoleSpec) DeepCopy() *HubbleRoleSpec {
	if in == nil {
		return nil
	}
	out := new(HubbleRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubbleRoleStatus) DeepCopyInto(out *HubbleRoleStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubbleRoleStatus.
func (in *HubbleRoleStatus) DeepCopy() *HubbleRoleStatus {
	if in == nil {
		return nil
	}
	out := new(HubbleRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubbleUser) DeepCopyInto(out *HubbleUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubbleUser.
func (in *HubbleUser) DeepCopy() *HubbleUser {
	if in == nil {
		return nil
	}
	out := new(HubbleUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HubbleUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubbleUserList) DeepCopyInto(out *HubbleUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HubbleUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubbleUserList.
func (in *HubbleUserList) DeepCopy() *HubbleUserList {
	if in == nil {
		return nil
	}
	out := new(HubbleUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HubbleUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubbleUserSpec) DeepCopyInto(out *HubbleUserSpec) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubbleUserSpec.
func (in *HubbleUserSpec) DeepCopy() *HubbleUserSpec {
	if in == nil {
		return nil
	}
	out := new(HubbleUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubbleUserStatus) DeepCopyInto(out *HubbleUserStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubbleUserStatus.
func (in *HubbleUserStatus) DeepCopy() *HubbleUserStatus {
	if in == nil {
		return nil
	}
	out := new(HubbleUserStatus)
	in.DeepCopyInto(out)
	return out
}
